---
- name: Common prepare
  ansible.builtin.import_playbook: ../prepare.yml

- name: Prepare ArchLinux
  hosts: all

  tasks:
    - name: Install prerequisites
      ansible.builtin.package:
        name:
          - sudo
          - unzip
          - tar
        state: present
