---
- name: Prepare controlling host
  hosts: localhost
  connection: local

  tasks:
    - name: Prepare CI environment
      when: lookup('env', 'CI') is truthy
      block:
        - name: Install OS packages on controlling host
          when: ansible_distribution != 'MacOSX'
          ansible.builtin.package:
            name: unzip
          become: true

        - name: Install netaddr dependency on controlling host
          ansible.builtin.pip:
            name: netaddr
          become: false

- name: Prepare ArchLinux
  hosts: all

  tasks:
    - name: Install prerequisites
      ansible.builtin.package:
        name:
          - sudo
          - unzip
          - tar
        state: present
