---
# File: tasks/install_hashi_repo.yml
#       Install Vault via HashiCorp Linux repository

- name: Add Vault/Hashicorp rpm repo
  yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: "{{ vault_repository_url }}"
    gpgkey: "{{ vault_repository_key_url }}"
    gpgcheck: true
    enabled: true
  become: true
  when: ansible_pkg_mgr in ['yum', 'dnf']

- name: Add Vault/Hashicorp apt key
  become: true
  apt_key:
    url: "{{ vault_repository_key_url }}"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Add Vault/Hashicorp apt repo
  become: true
  apt_repository:
    repo: "deb {{ vault_repository_url }} {{ ansible_distribution_release }} main"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install Vault package
  package:
    name: "{{ _vault_repo_pkg }}"
    state: present
  become: true
  vars:
    _vault_repo_pkg: "{% if (ansible_pkg_mgr in ['yum', 'dnf']) %}\
                  vault-{{ vault_version }}\
                {% elif (ansible_pkg_mgr == 'apt') %}\
                  vault={{ vault_version }}\
                {% else %}\
                  vault={{ vault_version }}\
                {% endif %}"

- name: Mask default Vault config from package
  become: true
  copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/vault.d/vault.hcl
    content: |
      # Placeholder to mask default RPM/DPKG Vault config file.
      #
      # Package-installed config would interfere with Ansible-managed config files
      # in this directory. Keeping an empty placeholder prevents package updates
      # from re-installing the default config.
  when: ansible_pkg_mgr in ['yum', 'dnf', 'apt']
