---
# File: tasks/install_hashi_repo.yml
#       Install Vault via HashiCorp Linux repository

- name: Add Vault/Hashicorp rpm repo
  yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: "{{ vault_repository_url }}"
    gpgkey: "{{ vault_repository_key_url }}"
    gpgcheck: true
    enabled: true
  become: true
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']
    - not vault_rhsm_repo_id

- name: Add Vault/Hashicorp apt key
  apt_key:
    url: "{{ vault_repository_key_url }}"
    state: present
  become: true
  when: ansible_pkg_mgr == 'apt'

- name: Add Vault/Hashicorp apt repo
  apt_repository:
    repo: "deb {{ vault_repository_url }} {{ ansible_distribution_release }} main"
    state: present
  become: true
  when: ansible_pkg_mgr == 'apt'

- name: Attach RHSM subscription / repo
  when: (vault_rhsm_repo_id)
  become: true
  block:
    - name: Check if Hashicorp/Vault RHSM repo subscription is enabled
      command:
        cmd: "subscription-manager list --consumed --matches={{ vault_rhsm_subscription_name | quote }} --pool-only"
      register: _subscription_manager_consumed
      changed_when: false
      when: (vault_rhsm_subscription_name)

    - name: Find Hashicorp/Vault RHSM repo subscription pool id
      command:
        cmd: "subscription-manager list --available --matches={{ vault_rhsm_subscription_name | quote }} --pool-only"
      register: _subscription_manager_available
      changed_when: false
      when:
        - (vault_rhsm_subscription_name)
        - _subscription_manager_consumed.stdout | length <= 0

    - name: Attach Hashicorp/Vault RHSM subscription
      command:
        cmd: "subscription-manager attach --pool={{ _subscription_manager_available.stdout }}"
      register: _subscription_manager_attach
      changed_when: _subscription_manager_attach.stdout is search('Successfully attached a subscription')
      failed_when: _subscription_manager_attach.stdout is search('could not be found')
      when:
        - (vault_rhsm_subscription_name)
        - _subscription_manager_consumed.stdout | default() | length <= 0
        - _subscription_manager_available.stdout | default() | length > 0

    - name: Enable RHSM repository
      rhsm_repository:
        name: "{{ vault_rhsm_repo_id }}"
        state: enabled

- name: Ensure Enterprise package is not present when OSS is desired and vice versa
  package:
    name: "{{ 'vault' ~ ('-enterprise' if not (vault_enterprise | bool) else '') }}"
    state: absent
  become: true

- name: "Install Vault package {{ _vault_repo_pkg }}"
  package:
    name: "{{ _vault_repo_pkg }}"
    state: present
  become: true
  vars:
    _vault_repo_pkg: "{% if (ansible_pkg_mgr in ['yum', 'dnf']) %}\
                  vault{{ '-enterprise' if vault_enterprise }}-{{ vault_version }}{{ vault_version_repo_suffix }}\
                {% elif (ansible_pkg_mgr == 'apt') %}\
                  vault{{ '-enterprise' if vault_enterprise }}={{ vault_version }}{{ vault_version_repo_suffix }}{{ vault_version_debian_repo_suffix }}\
                {% else %}\
                  vault{{ '-enterprise' if vault_enterprise }}={{ vault_version }}{{ vault_version_repo_suffix }}\
                {% endif %}"
  notify: Restart vault

- name: Mask default Vault config from package
  become: true
  copy:
    owner: root
    group: root
    mode: "{{ vault_harden_file_perms | ternary('0444', '0644') }}"
    dest: /etc/vault.d/vault.hcl
    content: |
      # Placeholder to mask default RPM/DPKG Vault config file.
      #
      # Package-installed config would interfere with Ansible-managed config files
      # in this directory. Keeping an empty placeholder prevents package updates
      # from re-installing the default config.
  when: ansible_pkg_mgr in ['yum', 'dnf', 'apt']

- name: Harden binary perms
  become: true
  ansible.builtin.file:
    path: "{{ vault_bin_path }}/vault"
    mode: "0755" # Package default is 0775
    owner: root # Package default
    group: root # Package default
  when: vault_harden_file_perms

- name: Delete vault.env
  become: true
  ansible.builtin.file:
    state: absent
    path: /etc/vault.d/vault.env
  when: vault_harden_file_perms

- name: Harden perms of default cert/key
  ansible.builtin.file:
    path: "/opt/vault/tls/{{ item }}"
    mode: "0400"
  with_items:
    - tls.crt
    - tls.key
  when:
    - vault_harden_file_perms
    - not vault_tls_disable
    - not vault_tls_copy_keys

- name: Delete default cert/key
  become: true
  ansible.builtin.file:
    state: absent
    path: "/opt/vault/tls/{{ item }}"
  with_items:
    - tls.crt
    - tls.key
  when: vault_tls_disable or vault_tls_copy_keys
