---
platforms:
  - name: debian-11
    groups:
      - vault_raft_servers
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-11_repo
    groups:
      - vault_raft_servers
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    host_vars:
      debian-11:
        vault_disable_api_health_check: true
        vault_enterprise: true
        vault_install_hashi_repo: false
      debian-11_repo:
        vault_disable_api_health_check: true
        vault_enterprise: true
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
        vault_group: vault
