---
- name: Prepare Debian
  hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap Python
      ansible.builtin.raw: "test -e /usr/bin/python || apt-get install --update python3 -y"
      changed_when: true

- name: Common prepare
  ansible.builtin.import_playbook: ../prepare.yml
