---
platforms:
  - name: debian-8
    groups:
      - vault_raft_servers
    image: dokken/debian-8
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-8_repo
    groups:
      - vault_raft_servers
    image: dokken/debian-8
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python2.7
    host_vars:
      debian-8_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
