---
- name: Bootstrap Python
  hosts: all
  gather_facts: false
  tasks:
    # default /usr/bin/python3 on EL8 is 3.6, too old for current ansible-core modules
    - name: Install python3.11
      ansible.builtin.raw: "test -e /usr/bin/python3.11 || (dnf install -y python3.11 || yum install -y python3.11)"
      changed_when: true

- name: Common prepare
  ansible.builtin.import_playbook: ../../prepare.yml

- name: Prepare AlmaLinux
  hosts: all
  tasks:
    - name: Set Permission on /etc/shadow
      ansible.builtin.file:
        path: /etc/shadow
        mode: "0640"
        owner: root
        group: root
