---
platforms:
  - name: rockylinux-9
    groups:
      - vault_raft_servers
    image: dokken/rockylinux-9
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: rockylinux-9_repo
    groups:
      - vault_raft_servers
    image: dokken/rockylinux-9
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    host_vars:
      rockylinux-9_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
        vault_group: vault
