---
platforms:
  - name: amazonlinux-2022
    groups:
      - amazonlinux-2022
    image: dokken/amazonlinux-2022
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2022-repo
    groups:
      - amazonlinux-2022-repo
      - repo
    image: dokken/amazonlinux-2022
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2022-enterprise
    groups:
      - amazonlinux-2022-enterprise
      - enterprise
    image: dokken/amazonlinux-2022
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2022-repo-enterprise
    groups:
      - amazonlinux-2022-repo-enterprise
      - repo
      - enterprise
    image: dokken/amazonlinux-2022
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
provisioner:
  inventory:
    links:
      group_vars: ../inventory/group_vars/
