---
- name: Prepare
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages
      when: ansible_distribution != 'MacOSX'
      package:
        name: unzip
      become: true

    - name: Install netaddr dependency on controlling host
      pip:
        name: netaddr
      become: false
