---
# File: site.yml - Example Vault server playbook (Filesystem storage)

- name: Install Vault Vagrant Development Server
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-community.ansible-vault, vault_backend: file}
