---
platforms:
  - name: amazonlinux-2-version-lock
    groups:
      - vault_raft_servers
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /sbin/init
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  playbooks:
    prepare: prepare.yml
  inventory:
    host_vars:
      amazonlinux-2-version-lock:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
        vault_group: vault
        vault_version_lock: true
