---
- name: Bootstrap Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 3.8
      ansible.builtin.raw: >-
        test -x /usr/bin/python3.8 || amazon-linux-extras install -y python3.8
      changed_when: true

- name: Common prepare
  ansible.builtin.import_playbook: ../../prepare.yml
