---
platforms:
  - name: centos-7
    groups:
      - vault_raft_servers
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    cgroup_parent: docker.slice
  - name: centos-7_repo
    groups:
      - vault_raft_servers
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    host_vars:
      centos-7_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
