---
platforms:
  - name: debian-11
    groups:
      - debian-11
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-11-enterprise
    groups:
      - debian-11-enterprise
      - enterprise
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-11-repo
    groups:
      - debian-11-repo
      - repo
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-11-repo-enterprise
    groups:
      - debian-11-repo-enterprise
      - repo
      - enterprie
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
provisioner:
  inventory:
    links:
      group_vars: ../inventory/group_vars/
