---
platforms:
  - name: debian-10
    groups:
      - vault_raft_servers
    image: dokken/debian-10
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-10_repo
    groups:
      - vault_raft_servers
    image: dokken/debian-10
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    host_vars:
      debian-10_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
        vault_group: vault
