---
platforms:
  - name: debian-10
    groups:
      - debian-10
    image: dokken/debian-10
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-10-enterprise
    groups:
      - debian-10-enterprise
      - enterprise
    image: dokken/debian-10
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-10-repo
    groups:
      - debian-10-repo
      - repo
    image: dokken/debian-10
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-10-repo-enterprise
    groups:
      - debian-10-repo-enterprise
      - repo
      - enterprise
    image: dokken/debian-10
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
provisioner:
  inventory:
    links:
      group_vars: ../inventory/group_vars/
