---
platforms:
  - name: amazonlinux-2
    groups:
      - vault_raft_servers
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2_repo
    groups:
      - vault_raft_servers
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    host_vars:
      amazonlinux-2_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
        vault_group: vault
