---
platforms:
  - name: amazonlinux-2
    groups:
      - amazonlinux-2
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2-repo
    groups:
      - amazonlinux-2-repo
      - repo
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2-enterprise
    groups:
      - amazonlinux-2-enterprise
      - enterprise
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: amazonlinux-2-repo-enterprise
    groups:
      - amazonlinux-2-repo-enterprise
      - repo
      - enterprise
    image: dokken/amazonlinux-2
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
provisioner:
  inventory:
    links:
      group_vars: ../inventory/group_vars/
