---
name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:

env:
  ANSIBLE_FORCE_COLOR: '1'
  PY_COLORS: '1'

jobs:
  discover-scenarios:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.set-scenarios.outputs.scenarios }}
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Discover scenarios
        id: set-scenarios
        # Find path to all scenarios
        run: |
          export scenarios="[`for x in $(ls -1 molecule -I _tests -I '*.yml'); do echo "'$x'"; done | tr '\n' ',' | sed '$s/,$//'`]"
          echo "::set-output name=scenarios::$scenarios"

  lint:
    runs-on: ubuntu-latest
    needs:
      - discover-scenarios
    strategy:
      matrix:
        scenario:
          - ${{ fromJson(needs.discover-scenarios.outputs.scenarios)[0] }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: lint
          molecule_args: --scenario-name ${{ matrix.scenario }}

  test:
    needs:
      - lint
      - discover-scenarios
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.discover-scenarios.outputs.scenarios) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
