---
- name: Bootstrap Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python3
      ansible.builtin.raw: "test -e /usr/bin/python3 || (dnf install -y python3 || yum install -y python3)"
      changed_when: true

- name: Common prepare
  ansible.builtin.import_playbook: ../../prepare.yml
